# Site settings
title: ML4CI
subtitle: Machine Learning for Causal Inference
description: |
    This course is ... . 
    Together, these tools can be used to ... . By the end of the course students will have learned ... . 
    ... . 
baseurl: "/ML4CI" # the github directory
url: "https://ainaimi.github.io/" # the base hostname & protocol for your site

# host the syllabus on google docs
# File: Publish to Web
syllabus_url: #
githubdir: "ainaimi/ML4CI"

# Author/user information
email: ashley.naimi@emory.edu
twitter_username: ashley_naimi
github_username:  ainaimi
authorurl: "https://bit.ly/3GFu2o1"
address: |
    Emory University
    Department of Biostatistics and Bioinformatics
    1518 Clifton Rd. NE
    Atlanta, GA 30322

# Use collection to manage records
collections: 
    recordings:
        output: true
        permalink: /:collection/:name

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
